id = "Sulayre.Lure"
name = "Lure"
description = "API to make adding content to WEBFISHING easier, faster and compatible."
version = "4.2.1"
homepage = "https://github.com/Sulayre/WebfishingLure"
author = "Sulayre, ZeaTheMays and GitHub Contributors"

icon = "icon.png"
readme = "README.md"

# both are optional here, pick what you want
[project]
csharp = "./Sulayre.Lure/Sulayre.Lure.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
